--1.TOTAL REVENUE.

-- This query calculates the total revenue generated by the business.
-- Revenue is calculated by multiplying quantity sold with selling price.
-- Order details table is joined with products table to get product prices.'

SELECT  
    SUM(o.quantity * p.selling_price) AS total_revenue
	FROM order_details o
    JOIN products p
    ON  o.product_id = p.product_id;
    
