6.--CATEGORY- WISE  REVENUE /SALES.'

-- This query calculates total revenue generated by each product category.
-- The order_details table is joined with products to get the selling price of each product.
-- Revenue for each category is calculated by summing quantity × selling price for all products in that category.
-- GROUP BY p.category ensures revenue is aggregated category-wise,
-- allowing analysis of which categories contribute most to sales.

SELECT TRIM(LOWER(p.category))AS category,
    SUM(od.quantity * p.selling_price) AS Category_wise_revenue
    FROM order_details od
    JOIN products p
    ON  od.product_id = p.product_id
    GROUP BY TRIM(LOWER(p.category));

